# Generated by Django 6.0.4 on 2026-05-27 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название дисциплины')),
                ('duration', models.PositiveIntegerField(verbose_name='длительность (в часах)')),
                ('curriculum', models.FileField(blank=True, null=True, upload_to='curricula/', verbose_name='учебный план')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='название группы')),
                ('course', models.CharField(choices=[('1', '1 курс'), ('2', '2 курс'), ('3', '3 курс'), ('4', '4 курс')], max_length=1, verbose_name='курс')),
            ],
            options={
                'verbose_name': 'Учебная группа',
                'verbose_name_plural': 'Учебные группы',
                'ordering': ['course'],
                'indexes': [models.Index(fields=['course'], name='students_gr_course_994371_idx')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=40, verbose_name='фамилия')),
                ('first_name', models.CharField(max_length=20, verbose_name='имя')),
                ('patronymic', models.CharField(blank=True, max_length=40, null=True, verbose_name='отчество')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='аккаунт')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.group', verbose_name='учебная группа')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(blank=True, max_length=200, verbose_name='описание курса')),
                ('course_start', models.DateField(blank=True, null=True, verbose_name='дата начала')),
                ('course_end', models.DateField(blank=True, null=True, verbose_name='дата завершения')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_courses', to=settings.AUTH_USER_MODEL, verbose_name='преподаватель')),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='students.discipline', verbose_name='дисциплина')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='students.group', verbose_name='учебная группа')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['discipline__title'],
                'indexes': [models.Index(fields=['discipline'], name='students_co_discipl_1b1155_idx'), models.Index(fields=['group'], name='students_co_group_i_35850f_idx'), models.Index(fields=['teacher'], name='students_co_teacher_6892df_idx')],
            },
        ),
    ]
