# Generated by Django 6.0.4 on 2026-05-23 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_group_student_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='course',
            new_name='year',
        ),
    ]
