# Generated by Django 6.0.4 on 2026-05-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_course_group_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['year', '-title']},
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['year'], name='students_gr_year_dcba7f_idx'),
        ),
    ]
