# Generated by Django 6.0.4 on 2026-06-04 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название дисциплины')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность')),
                ('curriculum', models.FileField(blank=True, null=True, upload_to='curriculums/', verbose_name='Учебный план')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего обновления')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
                'ordering': ['updated_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, verbose_name='Код курса')),
                ('about', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание курса')),
                ('course_start', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('course_end', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='students.group', verbose_name='Учебная группа')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='staff.teacher', verbose_name='Преподаватель')),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.discipline', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='courses_cou_code_612388_idx'), models.Index(fields=['discipline'], name='courses_cou_discipl_aac634_idx'), models.Index(fields=['group'], name='courses_cou_group_i_ff5d94_idx')],
            },
        ),
    ]
