# Generated by Django 6.0.5 on 2026-05-27 19:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название дисциплины')),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Длительность')),
                ('curriculum', models.FileField(blank=True, null=True, upload_to='curriculums/', verbose_name='Учебный план')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
                'ordering': ['updated_at', 'created_at'],
                'indexes': [models.Index(fields=['title'], name='discipline_title_idx')],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=15, verbose_name='Код курса')),
                ('about', models.CharField(blank=True, max_length=200, verbose_name='Описание курса')),
                ('course_start', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('course_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='students.group', verbose_name='Группа')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='staff.teacher', verbose_name='Преподаватель')),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.discipline', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['discipline__title', 'code'],
                'indexes': [models.Index(fields=['code'], name='course_code_idx'), models.Index(fields=['course_start'], name='course_start_idx'), models.Index(fields=['course_end'], name='course_end_idx')],
            },
        ),
    ]
