# Generated by Django 6.0.5 on 2026-06-03 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('duration', models.PositiveIntegerField(verbose_name='длительность')),
                ('curriculum', models.FileField(blank=True, null=True, upload_to='curriculums/', verbose_name='учебный план')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'дисциплина',
                'verbose_name_plural': 'дисциплины',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, verbose_name='код курса')),
                ('about', models.CharField(blank=True, max_length=200, verbose_name='описание')),
                ('course_start', models.DateField(blank=True, null=True, verbose_name='дата начала')),
                ('course_end', models.DateField(blank=True, null=True, verbose_name='дата завершения')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='students.group', verbose_name='учебная группа')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='staff.teacher', verbose_name='преподаватель')),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.discipline', verbose_name='дисциплина')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
                'ordering': ['discipline__title'],
                'indexes': [models.Index(fields=['code'], name='courses_cou_code_612388_idx'), models.Index(fields=['group'], name='courses_cou_group_i_ff5d94_idx'), models.Index(fields=['teacher'], name='courses_cou_teacher_ef24fb_idx')],
            },
        ),
    ]
