# Generated by Django 6.0.4 on 2026-05-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterField(
            model_name='discipline',
            name='duration',
            field=models.PositiveSmallIntegerField(verbose_name='Длительность'),
        ),
    ]
