# Generated by Django 6.0.4 on 2026-05-29 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderingnumber', models.PositiveIntegerField(verbose_name='Порядковый номер')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержание')),
                ('duration', models.PositiveBigIntegerField(verbose_name='Продолжительность')),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.discipline', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['discipline', 'orderingnumber'],
                'constraints': [models.UniqueConstraint(fields=('discipline', 'orderingnumber'), name='orderingnumber_per_discipline')],
            },
        ),
    ]
