# Generated by Django 6.0.4 on 2026-05-21 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='code',
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.discipline')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_group', to='students.group')),
            ],
        ),
    ]
