# Generated by Django 6.0.4 on 2026-06-05 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['discipline__title', 'ordering_number', 'order'], 'verbose_name': 'Учебная тема', 'verbose_name_plural': 'Учебные темы'},
        ),
        migrations.AddField(
            model_name='topic',
            name='assignments_count',
            field=models.PositiveIntegerField(default=1, verbose_name='количество заданий'),
        ),
        migrations.AddField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.course', verbose_name='курс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='hours',
            field=models.PositiveIntegerField(default=2, verbose_name='часы'),
        ),
        migrations.AddField(
            model_name='topic',
            name='info_blocks',
            field=models.PositiveIntegerField(default=0, verbose_name='блоки информации'),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='пройдено'),
        ),
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='порядок'),
        ),
        migrations.AddField(
            model_name='topic',
            name='tests_count',
            field=models.PositiveIntegerField(default=0, verbose_name='количество тестов'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(verbose_name='содержание темы'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='courses.discipline', verbose_name='дисциплина'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='количество часов'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='ordering_number',
            field=models.PositiveIntegerField(default=0, verbose_name='порядковый номер'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=200, verbose_name='название темы'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('ordering_number', 'discipline')},
        ),
    ]
