# Generated by Django 6.0.5 on 2026-05-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disclipline',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='Продолжительность'),
        ),
    ]
