# Generated by Django 6.0.4 on 2026-06-06 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering_number', models.PositiveIntegerField(verbose_name='Порядковый номер')),
                ('title', models.CharField(max_length=50, verbose_name='Название темы')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('duration', models.PositiveIntegerField(verbose_name='Количество часов')),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.discipline', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['discipline', 'ordering_number'],
                'constraints': [models.UniqueConstraint(fields=('ordering_number', 'discipline'), name='unique_topic_ordering_in_discipline')],
            },
        ),
    ]
