# Generated by Django 6.0.4 on 2026-05-31 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название темы')),
                ('content', models.TextField(verbose_name='содержание темы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('hours', models.PositiveIntegerField(default=2, verbose_name='часы')),
                ('is_completed', models.BooleanField(default=False, verbose_name='пройдено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.course', verbose_name='курс')),
            ],
            options={
                'verbose_name': 'Учебная тема',
                'verbose_name_plural': 'Учебные темы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ControlPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание задания')),
                ('max_score', models.PositiveIntegerField(default=10, verbose_name='максимальный балл')),
                ('student_score', models.PositiveIntegerField(default=0, verbose_name='полученный балл')),
                ('status', models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе'), ('submitted', 'Сдано'), ('passed', 'Пройдено')], default='not_started', max_length=20, verbose_name='статус')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_points', to='courses.topic', verbose_name='тема')),
            ],
            options={
                'verbose_name': 'Контрольная точка',
                'verbose_name_plural': 'Контрольные точки',
                'ordering': ['order'],
            },
        ),
    ]
