# Generated by Django 6.0.4 on 2026-05-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_topic_controlpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='assignments_count',
            field=models.PositiveIntegerField(default=1, verbose_name='количество заданий'),
        ),
        migrations.AddField(
            model_name='topic',
            name='info_blocks',
            field=models.PositiveIntegerField(default=0, verbose_name='блоки информации'),
        ),
        migrations.AddField(
            model_name='topic',
            name='tests_count',
            field=models.PositiveIntegerField(default=0, verbose_name='количество тестов'),
        ),
        migrations.AlterField(
            model_name='controlpoint',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе'), ('submitted', 'На проверке'), ('passed', 'Сдано')], default='not_started', max_length=20, verbose_name='статус'),
        ),
    ]
