# Generated by Django 6.0.5 on 2026-06-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата создания'),
        ),
    ]
