# Generated by Django 6.0.4 on 2026-05-23 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_discipline_options_alter_discipline_duration'),
        ('students', '0003_rename_course_group_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='code',
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('about', models.CharField(blank=True, max_length=200, null=True)),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.discipline')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.group')),
            ],
        ),
    ]
