# Generated by Django 6.0.4 on 2026-05-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_assignment_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание'),
        ),
    ]
