# Generated by Django 6.0.4 on 2026-05-20 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_discipline_remove_course_code_and_more'),
        ('students', '0003_alter_student_options_alter_group_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='learning_course', to='students.group'),
            preserve_default=False,
        ),
    ]
