# Generated by Django 6.0.5 on 2026-05-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='duration',
            field=models.PositiveIntegerField(default=2, verbose_name='длительность'),
            preserve_default=False,
        ),
    ]
