# Generated by Django 6.0.4 on 2026-05-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_assignment_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['assignment__topic__discipline'], 'verbose_name': 'Ответ студента', 'verbose_name_plural': 'Ответы студентов'},
        ),
    ]
