# Generated by Django 6.0.5 on 2026-05-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_topic_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['discipline__title', 'title']},
        ),
    ]
