# Generated by Django 6.0.4 on 2026-05-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_assignment_submission_topic_assignment_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='answer',
            field=models.TextField(default='some answer'),
            preserve_default=False,
        ),
    ]
