# Generated by Django 6.0.4 on 2026-06-06 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('students', '0002_student_alter_group_options_group_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('score', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment', verbose_name='Контрольная точка')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Ответ на контрольную точку',
                'verbose_name_plural': 'Ответы на контрольные точки',
                'ordering': ['assignment__topic__discipline', 'assignment__topic__ordering_number'],
            },
        ),
    ]
