# Generated by Django 6.0.4 on 2026-05-23 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='courses.discipline', verbose_name='дисциплина'),
        ),
        migrations.AddField(
            model_name='answer',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assignments.assignment', verbose_name='задание'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('student', 'assignment')},
        ),
    ]
