# Generated by Django 6.0.4 on 2026-05-27 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('content', '0001_initial'),
        ('students', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='topic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment', to='content.topic', verbose_name='тема'),
        ),
        migrations.AddField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment', verbose_name='контрольная точка'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students.student', verbose_name='студент'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('student', 'assignment')},
        ),
    ]
