# Generated by Django 6.0.4 on 2026-05-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='порядок'),
        ),
    ]
