# Generated by Django 6.0.4 on 2026-05-27 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering_number', models.PositiveIntegerField(verbose_name='порядковый номер')),
                ('title', models.CharField(max_length=50, verbose_name='название темы')),
                ('content', models.TextField(verbose_name='содержание')),
                ('duration', models.PositiveIntegerField(verbose_name='количество часов')),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='students.discipline', verbose_name='дисциплина')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['discipline', 'ordering_number'],
                'unique_together': {('ordering_number', 'discipline')},
            },
        ),
    ]
