# Generated by Django 6.0.5 on 2026-05-22 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_topic_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('weight', models.PositiveIntegerField(verbose_name='кол-во баллов')),
                ('updated_at', models.DateField(auto_now=True)),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.discipline')),
            ],
        ),
    ]
